sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: DfSfyGLx3eZAzJWPzhYdDo6Y4FPZ8EKMm6kh36R33giLMNyXv935kINFdPd+0uKN1LWzvsTI/zvt0PvFMVONap6O+FVmTLNiIAkVHhCzd53BfJLTo5YCNEiLZnqTQ1yJe6OC/ghpLEeNiQrLkfFCZnDmVKVO03Ek5dnc5Xig2ZUWE19CceBbJmZXGhihTbt2iJCVxsExx+bHF+sCfYckiIoh/RrE0CxnOWMnzKRQgKvo9TsgtskWR31MxgSaSpInyrlitWTU8Y7lxK6wFjqPpxXqibqluScncxqQJ6FHElrRFXXK6QT4fq9ftAgaYx28NpVY8B4jH9JeuHtfL5R/0HGqjm7ZWRJBIeAjH6G5WGmMEJ5lN3H2G1ckjrT7zBFtdKxOTgpPxOkb29cfsIorW27PyEOKHU5Avi/3ad7iJvzITmcy81v9jB97zBSETWbrYT5mLSXTyNSycTnH7OzIOT13Ccg4Oj86fZ64yb6rLXB2nlV7INTtzeeV/Tr/KzF+VnOdJDRu5hzCck/b9dkXfFMtrTjtG74MII9kRu/DFd7mYxyt7dEq75k33Lv6HNzPo+gPcFLV2ZOG7LUf7UcBDcqwZsLpwRWfosyoVh/xn7aXVeYHzC1wSiQLunUa9/zgX8eeVQOU4UyJhbcI2/h6SaDa14fihSbwiGX654RDpQo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Wacousta---a-tale-of-the-Pontiac-conspiracy---Volume-1_4719
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy